name: Deploy github-webhook-rds-sync

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/lambda_github_log_webhook.yml'
      - 'aws/lambda/github-logs-webhook/**'


concurrency:
  group: Deploy github-logs-webhook
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cd aws/lambda/github-logs-webhook
          make deployment
      - name: Deploy
        uses: appleboy/lambda-action@1e05c1377056f21ebb2ce69b910bc16b943c2a66
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: github-checks-status-updater
          timeout: 15
          zip_file: aws/lambda/github-logs-webhook/deployment.zip
